name: Getting Started
on:
  push:
    branches:
      - late

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install minimist
          npm install node-fetch
          
      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(node ./.bit/scripts/getProgress.js --repo=${{github.event.repository.name}} --owner=${{github.repository_owner}} )

      - name: Step 0
        if: ${{steps.vars.outputs.count == 0 && github.event.head_commit.message != 'Update progress'}}
        run: |
          node .bit/tests/test_late.js --repo=${{github.event.repository.name}} --user=${{github.repository_owner}}
      - name: Check for branch
        if: ${{steps.vars.outputs.count > 2 && github.event.head_commit.message != 'Update progress'}}
        run: |
          node .bit/tests/wrongbranch.js